In [1]:
import numpy as np
from tensorflow.keras.preprocessing.text import one_hot
from tensorflow.keras.layers import Embedding
from tensorflow.keras.utils import pad_sequences
from tensorflow.keras.models import Sequential

In [2]:
#sentences
sent=[  'the glass of milk',
     'the glass of juice',
     'the cup of tea',
    'I am a good boy',
     'I am a good developer',
     'understand the meaning of words',
     'your videos are good',]

In [3]:
sent

['the glass of milk',
 'the glass of juice',
 'the cup of tea',
 'I am a good boy',
 'I am a good developer',
 'understand the meaning of words',
 'your videos are good']

In [4]:
voc_size = 10000

In [5]:
one_hot_representataion = [one_hot(words, voc_size) for words in sent]
one_hot_representataion

[[1940, 3733, 6819, 3546],
 [1940, 3733, 6819, 7705],
 [1940, 5779, 6819, 2774],
 [7045, 398, 8680, 206, 6887],
 [7045, 398, 8680, 206, 4859],
 [1782, 1940, 666, 6819, 9264],
 [9940, 7613, 7877, 206]]

In [6]:
sent_length = 8
embedded_docs = pad_sequences(one_hot_representataion, padding = 'pre', maxlen = sent_length)
print(embedded_docs)

[[   0    0    0    0 1940 3733 6819 3546]
 [   0    0    0    0 1940 3733 6819 7705]
 [   0    0    0    0 1940 5779 6819 2774]
 [   0    0    0 7045  398 8680  206 6887]
 [   0    0    0 7045  398 8680  206 4859]
 [   0    0    0 1782 1940  666 6819 9264]
 [   0    0    0    0 9940 7613 7877  206]]


In [7]:
dim = 10

In [8]:
model = Sequential()
model.add(Embedding(voc_size, dim, input_length = sent_length))
model.compile('adam', 'mse')

/usr/local/lib/python3.12/dist-packages/keras/src/layers/core/embedding.py:97: UserWarning: Argument `input_length` is deprecated. Just remove it.
  warnings.warn(


In [9]:
model.summary()

Model: "sequential"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ embedding (Embedding)           │ ?                      │   0 (unbuilt) │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 0 (0.00 B)

 Trainable params: 0 (0.00 B)

 Non-trainable params: 0 (0.00 B)

In [10]:
model.predict(embedded_docs)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 192ms/step


array([[[-0.00039346, -0.02021128, -0.00635809,  0.01062198,
          0.02979386,  0.00674821,  0.01469121,  0.04178092,
          0.03043428, -0.03869226],
        [-0.00039346, -0.02021128, -0.00635809,  0.01062198,
          0.02979386,  0.00674821,  0.01469121,  0.04178092,
          0.03043428, -0.03869226],
        [-0.00039346, -0.02021128, -0.00635809,  0.01062198,
          0.02979386,  0.00674821,  0.01469121,  0.04178092,
          0.03043428, -0.03869226],
        [-0.00039346, -0.02021128, -0.00635809,  0.01062198,
          0.02979386,  0.00674821,  0.01469121,  0.04178092,
          0.03043428, -0.03869226],
        [-0.01045699,  0.03041947,  0.01740542, -0.04447211,
         -0.01712233,  0.00651544,  0.04150986, -0.03922347,
          0.00570061, -0.04695368],
        [-0.04346535, -0.03882325, -0.0081332 ,  0.04532376,
          0.04438089, -0.04942044, -0.03784771,  0.03777378,
          0.00847923,  0.00750744],
        [ 0.01380834, -0.01976698, -0.02791268,  0.0